site_name: ACBD-HCP BIDS fMRI Pipeline
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Overview: index.md
  - Table of contents: testing.md
  - Installation: installation.md
  - Usage: usage.md
  - Outputs: outputs.md
