blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/DCAN-Labs/abcd-hcp-pipeline
    about: Please ask and answer questions related to the ABCD-HCP pipeline usage here.